version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3010:3010"
    environment:
      - DATABASE_URL=mongodb+srv://Azazshah:Sirikotali01@cluster0.dw67swt.mongodb.net/flipi
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - rabbitmq
    volumes:
      - ./Backend:/app
      - /app/node_modules

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin

      
      - RABBITMQ_DEFAULT_PASS=password

  frontend:
    build: ./Frontend/App
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/App:/app
      - /app/node_modules